FROM ubuntu:20.04

#ARG RUNNER_VERSION
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y --no-install-recommends \
    curl \
    nodejs \ 
    wget \
    unzip \
    vim \
    git \
    azure-cli \
    jq \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3 \
    python3-venv \
    python3-dev \
    python3-pip \
    sudo
    
RUN useradd -m runner

COPY config-tool.sh /home/runner/
RUN chmod +x /home/runner/config-tool.sh
RUN /home/runner/config-tool.sh

RUN usermod -aG sudo runner
RUN usermod -aG docker runner

RUN echo '%sudo ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

RUN cd /home/runner && mkdir actions-runner && cd actions-runner \
    && curl -O -L https://github.com/actions/runner/releases/download/v2.309.0/actions-runner-linux-x64-2.309.0.tar.gz \
    && tar xzf ./actions-runner-linux-x64-2.309.0.tar.gz

RUN chown -R runner ~runner && /home/runner/actions-runner/bin/installdependencies.sh

ADD spin.sh spin.sh
RUN chmod +x spin.sh
# set the user to "runner" so all subsequent commands are run as the runner user
USER runner
ENTRYPOINT ["./spin.sh"]