name: Deploy VM

on:
  workflow_dispatch:

env:
  AZURE_RG: aca-ghr-test
  AZURE_LOCATION: westus2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Check for resource compliance
      uses: actions/azure-policy-scan@main
      with:
        scopes: |
          /subscriptions/34176af6-6df0-47ef-a8cb-99f46d66332c/resourceGroups/aca-ghr-test
        report-name: test-report