name: Bicep Compliance Scan against Azure Policy
on:
  workflow_dispatch

jobs:
  bicep-scan:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Policy Scan
        shell: pwsh
        run: |
          Install-Module Az -Scope CurrentUser
          Install-Module PSRule.Rules.Azure -Scope CurrentUser -AllowPrerelease
          Install-Module EnterprisePolicyAsCode -Scope CurrentUser

          cd ${{github.workspace}}\PSRule
      
          Export-AzPolicyResources -DefinitionsRootFolder .\ -Mode psrule -OutputFolder .\
          Export-AzPolicyAssignmentRuleData -AssignmentFile .\psrule.assignment.json -OutputPath .\ps-rule

          Assert-PSRule -InputPath ..\az-policy-scan\ -Module "PSRule.Rules.Azure" -Format File