name: Build and Publish GitHub Runner Docker Image

on:
  workflow_dispatch:

env:
  AZURE_RG: gh-actions-test
  AZURE_LOCATION: westus2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Login to ACR
      run: |
        az acr login --name ggracr.azurecr.io

    - name: build and publish Docker Image
      run: |
        cd ${{ github.workspace }}/github-runner/
        docker build -t ggracr.azurecr.io/github-runner:v4 .
        docker push ggracr.azurecr.io/github-runner:v4

