name: Azure container apps self hosted runner test

on:
  workflow_dispatch:

jobs:
  testRunner:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2

      - name: install az cli
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | bash

      - name: install bicep CLI
        run: |
          curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ./bicep
          sudo mv ./bicep /usr/local/bin/bicep

      - name: Display az CLI version
        run: |
          az --version