name: Azure container apps self hosted runner test

on:
  workflow_dispatch:

jobs:
  testRunner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install bicep CLI
        run: |
          curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ./bicep
          mv ./bicep /usr/local/bin/bicep

      - name: Display az CLI version
        run: |
          az --version
